package com.liveneo.etrepair.webservice.server.survey;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.8
 * 2016-04-14T11:16:01.864+08:00
 * Generated source version: 2.4.8
 * 
 */
@WebService(targetNamespace = "http://survey.ws.etrepair.com", name = "CaseInfoSoapBinding")
// @XmlSeeAlso({ObjectFactory.class})
public interface CaseInfoSoapBinding {
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendClaimInfo", targetNamespace = "http://survey.ws.etrepair.com",
            className = "com.liveneo.etrepair.webservice.server.survey.SendClaimInfo")
    @WebMethod
    @ResponseWrapper(localName = "sendClaimInfoResponse", targetNamespace = "http://survey.ws.etrepair.com",
            className = "com.liveneo.etrepair.webservice.server.survey.SendClaimInfoResponse")
    public java.lang.String sendClaimInfo(@WebParam(name = "DispatchRequest", targetNamespace = "") java.lang.String dispatchRequest);
}
