package com.liveneo.etrepair.webservice.client.hx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-04-13T17:43:43.166+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "Claim2DelegateServiceService", wsdlLocation = "http://10.100.135.169:8008/cxfServices/Claim2Delegate?wsdl",
        targetNamespace = "http://delegate.provider.webservice.interact.application.sinosoft.com/")
public class Claim2DelegateServiceService extends Service {
    public final static URL   WSDL_LOCATION;
    public final static QName SERVICE                   = new QName("http://delegate.provider.webservice.interact.application.sinosoft.com/",
                                                                "Claim2DelegateServiceService");
    public final static QName Claim2DelegateServicePort = new QName("http://delegate.provider.webservice.interact.application.sinosoft.com/",
                                                                "Claim2DelegateServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.100.135.169:8008/cxfServices/Claim2Delegate?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Claim2DelegateServiceService.class.getName()).log(java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}", "http://10.100.135.169:8008/cxfServices/Claim2Delegate?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Claim2DelegateServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Claim2DelegateServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Claim2DelegateServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns Claim2DelegateFacade
     */
    @WebEndpoint(name = "Claim2DelegateServicePort")
    public Claim2DelegateFacade getClaim2DelegateServicePort() {
        return super.getPort(Claim2DelegateServicePort, Claim2DelegateFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Claim2DelegateFacade
     */
    @WebEndpoint(name = "Claim2DelegateServicePort")
    public Claim2DelegateFacade getClaim2DelegateServicePort(WebServiceFeature... features) {
        return super.getPort(Claim2DelegateServicePort, Claim2DelegateFacade.class, features);
    }
}
