package com.liveneo.etrepair.webservice.client.hx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-04-13T17:43:43.157+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://delegateInterFacade.delegate.provider.webservice.interact.application.sinosoft.com/", name = "Claim2DelegateFacade")
@XmlSeeAlso({ ObjectFactory.class })
public interface Claim2DelegateFacade {
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "setCaseToNormal",
            targetNamespace = "http://delegateInterFacade.delegate.provider.webservice.interact.application.sinosoft.com/",
            className = "com.liveneo.etrepair.webservice.client.hx.SetCaseToNormal")
    @WebMethod
    @ResponseWrapper(localName = "setCaseToNormalResponse",
            targetNamespace = "http://delegateInterFacade.delegate.provider.webservice.interact.application.sinosoft.com/",
            className = "com.liveneo.etrepair.webservice.client.hx.SetCaseToNormalResponse")
    public java.lang.String setCaseToNormal(@WebParam(name = "request", targetNamespace = "") java.lang.String request) throws Exception_Exception;
}
