package com.liveneo.etrepair.webservice.client.hx;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-04-13T17:43:43.152+08:00
 * Generated source version: 2.7.18
 */
@WebFault(name = "Exception", targetNamespace = "http://delegateInterFacade.delegate.provider.webservice.interact.application.sinosoft.com/")
public class Exception_Exception extends java.lang.Exception {
    private com.liveneo.etrepair.webservice.client.hx.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.liveneo.etrepair.webservice.client.hx.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.liveneo.etrepair.webservice.client.hx.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.liveneo.etrepair.webservice.client.hx.Exception getFaultInfo() {
        return this.exception;
    }
}
